# SmartAudio 
bilibili:
  #          SESSDATA  ;  ,  ;     ,  ""
  sessdata: ""

audio2text:
  #  (FunASR )
  model: "iic/SenseVoiceSmall"

chat_server:
  openai:
    api_key: ""
    base_url: ""
    chat_model: ""
